version: '2'
services:
 # application
  rails_app:
    build: ./rails_app
    container_name: "rails_app"
    command: bundle exec rails s -p 3000 -b '0.0.0.0' -e production
    volumes:
      - ./rails_app:/rails_app
    stdin_open: true
    tty: true

 # web server
  nginx:
    build: 
      context: ./nginx
      dockerfile: "Dockerfile.production"
    container_name: "nginx"
    ports:
      - "80:80"
    depends_on:
      - rails_app
    volumes:
      - ./rails_app:/var/www/html

  # for browser
  chrome:
    container_name: "chrome"
    image: selenium/standalone-chrome-debug:3.141.59-gold
    ports:
      - 4444:4444 # for web
      - 5900:5900 # for vnc
    shm_size: 512m

  redis:
    build: ./redis
    volumes:
      - ./redis/data:/data
    command: redis-server /etc/redis/redis.conf
    container_name: "redis_server"
