version: '2'
services:
  db:
    image: mysql:5.7
    container_name: "db"
    environment:
      MYSQL_ROOT_PASSWORD: yasuda_app
      MYSQL_DATABASE: root

  rails_app:
    build: ./rails_app
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - ./rails_app:/rails_app
    ports:
      - "3000:3000"
    depends_on:
      - db
    stdin_open: true
    tty: true

  phpadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - db
    ports:
      - "9999:80"
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: sfk0105sql
