version: '2'
services:
  db:
    build: ./mysql
    container_name: "db"
    environment:
      MYSQL_ROOT_PASSWORD: yasuda_app
      MYSQL_DATABASE: root

  rails_app:
    build: ./rails_app
    container_name: "rails_app"
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - ./rails_app:/rails_app
    depends_on:
      - db
    stdin_open: true
    tty: true

  nginx:
    build: ./nginx
    container_name: "nginx"
    ports:
      - "3000:80"
    depends_on:
      - rails_app
    volumes:
      - ./nginx/log:/var/log/nginx

  phpadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - db
    ports:
      - "9999:80"
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: yasuda_app
