version: 2
jobs:
  build:
    # docker-composeがインストール済みの仮想マシンをプル
    machine:
      image: circleci/classic:edge
    steps:
      - checkout
      - run:
          name: Build Docker Container
          command: docker-compose build
      - run:
          name: Up Docker Compose
          command: docker-compose up -d
      - run:
          name: waiting DB connecting
          command: sleep 10
      - run:
          name: Set Up DB
          command: docker exec rails_app rails db:migrate:reset RAILS_ENV=test
      - run:
          name: DB Seed
          command: docker exec rails_app rails db:seed
      - run:
          name: Down Docker Container
          command: docker-compose down