version: 2
jobs:
  build:
    machine:
      image: circleci/classic:edge
    steps:
      - checkout
      - run:
          name: Setup dockerize
          command: bash .circleci/setup_dockerize.sh
      - run:
          name: Build Docker Container
          command: docker-compose build
      - run:
          name: Up Docker Compose
          command: docker-compose up -d
      - run:
         name: Wait for DB
         command: |
            docker run --network my_network \
              jwilder/dockerize -wait http://my_service/about/ -timeout 1m -wait-retry-interval 5s
      - run:
          name: Set Up DB
          command: docker exec -it rails_app bundle exec rails db:migrate:reset RAILS_ENV=test
      - run:
          name: DB Seed
          command: docker exec -it rails_app bundle exec rails db:seed RAILS_ENV=test
      - run:
          name: rails test
          command: docker exec -it rails_app bundle exec rails test
      - run:
          name: Eslint
          command: make eslint
      - run:
          name: Down Docker Container
          command: docker-compose down